//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoUser
    {
        public int id_photo { get; set; }
        public int id_user { get; set; }
        public string source { get; set; }
        public byte[] phot { get; set; }
    
        public virtual User User { get; set; }
    }
}
