//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int id_sale { get; set; }
        public System.DateTime sale_date { get; set; }
        public int id_client { get; set; }
        public int id_employee { get; set; }
        public int id_tour { get; set; }
        public int amount { get; set; }
        public int id_payment_type { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Payment_Type Payment_Type { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
